name: Terraform Lint Check and Commit

on:
  push:
    paths:
      - '**/*.tf'

jobs:
  tflint_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Install tflint
        run: |
          wget https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip
          unzip tflint_linux_amd64.zip
          sudo mv tflint /usr/local/bin/
          rm tflint_linux_amd64.zip

      - name: Run tflint
        run: |
          find . -type f -name '*.tf' -exec dirname {} \; | sort -u | xargs -I % sh -c 'cd % && tflint'

      - name: Commit changes
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.event.pusher.name }}"
          git add -u
          git commit -m "Auto linting Terraform files" || echo "Theres no changes to commit"
          git push origin ${{ github.ref }}